openapi: 3.0.1
info:
  title: Ainized-Style-Transfer 
  description:  |
    # This is an API server that uses deep learning to compose one image in the style of another image
    ---
    How to use:
      * send base image and style image to ainized style-transfer server
      
  version: 1.0.0
  license:
    name: "MIT"
    url: ""
servers:
  - url: ''

paths:
  /transfer:
    post:
      tags:
      - Style-transfer
      requestBody:
        required: true
        description: "send base and style images \n \n [sample base image](https://storage.googleapis.com/download.tensorflow.org/example_images/YellowLabradorLooking_new.jpg) \n \n [sample style image](https://storage.googleapis.com/download.tensorflow.org/example_images/Vassily_Kandinsky%2C_1913_-_Composition_7.jpg)"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                baseImage:
                  type: string
                  format: binary
                styleImage:
                  type: string
                  format: binary

            encoding:
              files:
                contentType: image/*
      responses:
         '200':
            description: success
            content:
              images/*:
                  schema:
                    type: string
                    format: binary
         '400':
            description: Bad request (Can not load images)
         '500':
            description: Server Side Error
